service:
  access_token_duration: 3000s
  refresh_token_duration: 604800s
  email_regexp: '^[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,4}$'

mysql:
  port: 3306
  database: "wallet_db"

http_port: 5002
http_shut_down_timeout: "5s"

publisher:
  retry_ttl: "5s"