service:
  access_token_duration: 3000s
  refresh_token_duration: 604800s
  email_regexp: '^[a-z0-9._%+\-]+@[a-z0-9.\-]+\.[a-z]{2,4}$'

mysql:
  port: 3306
  database: "wallet_db"

http_port: 5002
http_shut_down_timeout: "5s"

publisher:
  retry_ttl: "5s"

otel:
  service_name: "auth"
  environment: "stage"
  endpoint: "mini_wallet-otel-collector:4317"

outbox_worker:
  batch_interval: "5s"
  recovery_interval: "60s"
  lock_timeout: "60s"
  batch_size: 60
  concurrency: 6

outbox_service:
  lock_timeout: "20s"

grpc_server:
  port: 6002
  type: "tcp"
  shutdown_context_timeout: "10s"
  tls_enabled: false