http_port: 5002
http_shut_down_timeout: "3s"
subscriber_shutdown_timeout: "3s"

redis:
  host: "mini_wallet-redis"
  port: 6379

notification_service:
  ticket_ttl: "300s"

subscriber:
  retry_ttl: "5s"
  workers: 5
  max_retry: 3
  prefetch_count: 10
  handler_timeout: "10s"

otel:
  service_name: "notification"
  environment: "stage"
  endpoint: "mini_wallet-otel-collector:4317"