CREATE TABLE IF NOT EXISTS wallets (
     id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
     user_id BIGINT UNSIGNED NOT NULL UNIQUE,
     balance BIGINT NOT NULL DEFAULT 0,
     currency VARCHAR(10) NOT NULL DEFAULT 'IRR',
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);