services:
  wallet:
    build:
      context: .
      dockerfile: ./deployment/wallet/stage/Dockerfile
    container_name: mini_wallet-wallet
    profiles:
      - wallet
      - stage
    expose:
      - "5002"
    env_file: ./deployment/wallet/stage/.env
    environment:
      ENV: stage
      LOG_LEVEL: debug
      GIN_MODE: release
    networks:
      - docker_wallet-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5002/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  docker_wallet-network:
    external: true
