apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://mini_wallet-loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: "View Trace"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://mini_wallet-tempo:3200
    uid: tempo
    editable: false
    jsonData:
      lokiSearch:
        datasourceUid: loki
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        customQuery: true
        query: '{app=~".+"} | json | trace_id="${__trace.traceId}"'

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://mini_wallet-prometheus:9090
    editable: false