http:
  routers:
    docs:
      rule: "PathPrefix(`/docs`)"
      middlewares:
        - cb
        - strip-docs-prefix
      service: docs-service

    auth:
      rule: "PathPrefix(`/auth`)"
      middlewares:
        - cb
        - strip-auth-prefix
        - rate-limit
      service: auth-service

    wallet:
      rule: "PathPrefix(`/wallet`)"
      middlewares:
        - cb
        - strip-wallet-prefix
        - rate-limit
      service: wallet-service

    notification:
      rule: "PathPrefix(`/notification`)"
      middlewares:
        - cb
        - strip-notification-prefix
        - sse-headers
      service: notification-service

  middlewares:
    cb:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.5 || ResponseCodeRatio(500, 600, 0, 600) > 0.5"

    strip-docs-prefix:
      stripPrefix:
        prefixes:
          - "/docs"

    strip-auth-prefix:
      stripPrefix:
        prefixes:
          - "/auth"

    strip-wallet-prefix:
      stripPrefix:
        prefixes:
          - "/wallet"

    strip-notification-prefix:
      stripPrefix:
        prefixes:
          - "/notification"

    sse-headers:
      headers:
        customResponseHeaders:
          X-Accel-Buffering: "no"
          Cache-Control: "no-cache"
          Connection: "keep-alive"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

  services:
    docs-service:
      loadBalancer:
        servers:
          - url: "http://mini_wallet-docs:5002"
        healthCheck:
          path: /ready
          interval: 30s
          timeout: 5s

    auth-service:
      loadBalancer:
        servers:
          - url: "http://mini_wallet-auth:5002"
        healthCheck:
          path: /ready
          interval: 30s
          timeout: 5s

    wallet-service:
      loadBalancer:
        servers:
          - url: "http://mini_wallet-wallet:5002"
        healthCheck:
          path: /ready
          interval: 30s
          timeout: 5s

    notification-service:
      loadBalancer:
        servers:
          - url: "http://mini_wallet-notification:5002"
        healthCheck:
          path: /ready
          interval: 30s
          timeout: 5s