apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-auth-env-config
data:
  ENV: "{{ .Values.global.APP_ENV }}"
  LOG_LEVEL: "{{ .Values.global.APP_LOG_LEVEL }}"
  GIN_MODE: "{{ .Values.global.APP_GIN_MODE }}"

  AUTH_SERVICE_JWT__SECRET: "jwt123token!"

  AUTH_MYSQL_HOST: "host.docker.internal"
  AUTH_MYSQL_PORT: "33061"
  AUTH_MYSQL_USERNAME: "wallet_admin"
  AUTH_MYSQL_PASSWORD: "wallet_pass"

  AUTH_PUBLISHER_URL: "amqp://guest:guest@host.docker.internal:56721"

  AUTH_OTEL_ENDPOINT: "host.docker.internal:8317"